services:
  solr:
    image: solr:10.0.0
    container_name: opinion_solr
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/var/solr
      - ./src/solr/configs:/configs
    command: >
      solr-precreate reddit_ai /configs
    environment:
      - SOLR_HEAP=512m

volumes:
  solr_data:
